// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestHotel.Entities;

namespace TestHotel.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20191127140850_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0-preview3.19554.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TestHotel.Entities.Customer", b =>
                {
                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.HasKey("Phone");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TestHotel.Entities.Room", b =>
                {
                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<bool>("State")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Number");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("TestHotel.Entities.Users", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Login");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TestHotel.Entities.Visitors", b =>
                {
                    b.Property<Guid>("Record")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Arrive")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Leave")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Record");

                    b.HasIndex("Number");

                    b.HasIndex("Phone");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("TestHotel.Entities.Visitors", b =>
                {
                    b.HasOne("TestHotel.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("Number")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TestHotel.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("Phone")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
